### ISSUE TITLE
Failed to import winapi32

### ISSUE THREAD

**Issue by Rajarshi1001** [maxfrei750/paddle#2] opened 2022-07-22 12:19 UTC
While executing the command `jupyter lab`, it throws an error `DLL load failed while importing win32api: The specified procedure could not be found`. I ahve tried installing `conda install -c anaconda pywin32` but the same issue persists.
Could you please provide a reply to this issue?

**Comment by maxfrei750** [comment] 2022-07-22 13:28
Unfortunately, I think that you're encountering an issue with your system/`jupyter`, not with `paddle`, so I can't be of any help. Especially since I'm on Linux and can't reproduce your error. That being said, `paddle` was already successfully deployed on Windows, so there must be a way.

PS: The second (at least for me) Google result for `jupyter DLL load failed while importing win32api: The specified procedure could not be found` looks promising: https://stackoverflow.com/questions/68226255/how-to-fix-dll-load-failed-while-importing-win32api-in-jupyter-notebook-after

I'll close this for now.

**Closed as completed by maxfrei750** 2022-07-22 13:28 UTC
