### ISSUE TITLE
mpac.zip is not a zip file

### ISSUE THREAD

**Issue by Rajarshi1001** [maxfrei750/paddle#5] opened 2022-07-22 18:38 UTC
I have tried running the notebook __analyze_dataset.ipynb__ . While executing the cell
![image](https://user-images.githubusercontent.com/79023293/180502751-47653cb2-14d5-4a80-9312-db04613deaad.png)
I get the following issue, the dataset seems to be private or remove by the owner.
![image](https://user-images.githubusercontent.com/79023293/180502698-1cde96e4-0797-46f1-b43c-190b425eb4b5.png)

**Comment by maxfrei750** [comment] 2022-07-22 19:14
Apparently, the university broke my download link. Thanks for letting me know. I just committed a fix. Please pull the new main version and let me know if it works now.

**Comment by Rajarshi1001** [comment] 2022-07-22 19:52
I tried running the train function but it initially asked for the __wandb__ API key.
This gave the following error
![image](https://user-images.githubusercontent.com/79023293/180517196-5fab3aec-0e74-421b-ad7a-608419ccadc2.png)

Could you please give a detailed instructions to run the notebooks because there seems to multiple issues in the repo

**Comment by Rajarshi1001** [comment] 2022-07-22 19:54
the __file is not a zip file__ issue still persists

**Comment by Rajarshi1001** [comment] 2022-07-22 19:57
the load model also throws an error
![image](https://user-images.githubusercontent.com/79023293/180517876-458fbade-fb30-4863-82aa-2f8a5f3a52eb.png)

**Comment by maxfrei750** [comment] 2022-07-23 18:27
There were indeed a few errors, which resulted from changes in the code base. That's what I get for not having tests and not using docker for this project. I fixed all problems and on my system, all demos run flawlessly again. That being said, I was not able to reproduce the `File is not a zip file`. So please pull the recent commits, recreate your conda environment (see updated instructions in readme), test again and let me know the results.

**Comment by maxfrei750** [comment] 2022-07-26 06:32
@Rajarshi1001 Did the update of the demos fix your `File is not a zip file` error? If so, then please close this issue.

**Comment by maxfrei750** [comment] 2022-08-08 13:03
Closing, since the problem seems to be resolved.

**Closed as completed by maxfrei750** 2022-08-08 13:03 UTC
